name: Build and Sign Android APK

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build React app
        working-directory: frontend
        run: npm run build

      # Patch gradle files to avoid Java 21 compatibility issues
      - name: Patch all Gradle files to use Java 17
        run: |
          find . -type f \( -name "*.gradle" -o -name "*.gradle.kts" \) -print0 | xargs -0 sed -i 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g'
          find . -type f \( -name "*.gradle" -o -name "*.gradle.kts" \) -print0 | xargs -0 sed -i 's/sourceCompatibility[ ]*=[ ]*21/sourceCompatibility = 17/g'
          find . -type f \( -name "*.gradle" -o -name "*.gradle.kts" \) -print0 | xargs -0 sed -i 's/targetCompatibility[ ]*=[ ]*21/targetCompatibility = 17/g'
          find . -type f \( -name "*.gradle" -o -name "*.gradle.kts" \) -print0 | xargs -0 sed -i 's/sourceCompatibility[ ]*=[ ]*JavaVersion\.VERSION_21/sourceCompatibility = JavaVersion.VERSION_17/g'
          find . -type f \( -name "*.gradle" -o -name "*.gradle.kts" \) -print0 | xargs -0 sed -i 's/targetCompatibility[ ]*=[ ]*JavaVersion\.VERSION_21/targetCompatibility = JavaVersion.VERSION_17/g'

      # 检查还有没有 VERSION_21
      - name: 检查是否还有 VERSION_21
        run: |
          grep -r --include="*.gradle*" "VERSION_21" . || true
          grep -r --include="*.gradle*" "sourceCompatibility" . || true
          grep -r --include="*.gradle*" "targetCompatibility" . || true

      - name: Build APK
        working-directory: frontend/android
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: frontend/android/app/build/outputs/apk/debug/app-debug.apk
